[package]
name = "bytebit/linalg"
description = "A simple script to implement linear algebra functions not provided by the Lua standard API, developed especially for use on Roblox"
version = "0.0.1"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
testez = "roblox/testez@0.4.1"